name: healthcaresystem
services:
  healthcaresystem.api:
    container_name: healthcaresystem.api
    image: healthcaresystem.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyBestHttpsPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: HealthcareSystem.Api/Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro
  healthcaresystem.database:
    container_name: healthcaresystem.databasew
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "_MySecretKey12345_"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: