name: healthcaresystem
services:
  healthcaresystem.api:
    container_name: healthcaresystem.api
    image: healthcaresystem.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyBestHttpsPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: HealthcareSystem.Api/Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro
  healthcaresystem.client:
    container_name: healthcaresystem.client
    image: healthcaresystem.client
    ports:
      - "4400:80"
    build:
      context: ./HealthcareSystem.Client
      dockerfile: Dockerfile
  healthcaresystem.database:
    container_name: healthcaresystem.database
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "_MySecretKey12345_"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  healthcaresystem.smtp:
    container_name: healthcaresystem.smtp
    image: rnwood/smtp4dev
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  database:
  smtp4dev-data: